### ISSUE TITLE
Allow set which folder to look for yarn.lock file

### ISSUE THREAD

**Issue by iagobruno** [c-hive/gha-yarn-cache#13]
Example:

```yml
  - uses: c-hive/gha-yarn-cache@v2
    with:
      directory: server
```
