### ISSUE TITLE
Caching with Cypress jobs

### ISSUE THREAD

**Issue by edouard-lopez** [c-hive/gha-yarn-cache#14]
Thanks for your project!

I'm trying to set it up on my workflok, it seem to work for my first job `test-unit` but not for the other one `test-e2e-chrome`.

### Workflow

```
name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  test-unit:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache yarn
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install

      - name: Unit tests and Component tests
        run: yarn test

  test-e2e-chrome:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome90-ff88
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache yarn
        uses: c-hive/gha-yarn-cache@v2

      - name: End-to-end testing
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: "http://localhost:3000"
          browser: chrome
        env:
          NODE_ENV: development
```

### `test-unit job`

The cache is found, no problem

```
Run c-hive/gha-yarn-cache@v2
/usr/bin/uname
Linux
/usr/local/bin/yarn config get cacheFolder
undefined
/usr/local/bin/yarn cache dir
/home/runner/.cache/yarn/v6
Cache keys: Linux-yarn-cache-38ebe111513c9c0867d5bc4b64d92963, Linux-yarn-cache-
Cache Size: ~101 MB (105626556 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/5283ae91-2de5-4641-b499-4207abbfda7b/cache.tzst -P -C /home/runner/work/webchat-v2/webchat-v2
Cache restored from key: Linux-yarn-cache-38ebe111513c9c0867d5bc4b64d92963
```

### `test-e2e-chrome`

For my second job, I'm using your action then [cypress-io's one](https://github.com/cypress-io/github-action#custom-cache-key), but the cache is not found :/

```
Run c-hive/gha-yarn-cache@v2
/usr/bin/docker exec  8307ae2381cdf5705f25682ac543d14020f56b9d68a6b1138d10cc7cdcbf9d42 sh -c "cat /etc/*release | grep ^ID"
/bin/uname
Linux
/usr/local/bin/yarn config get cacheFolder
undefined
/usr/local/bin/yarn cache dir
/usr/local/share/.cache/yarn/v6
Cache keys: Linux-yarn-cache-38ebe111513c9c0867d5bc4b64d92963, Linux-yarn-cache-
Cache not found
```

## Question

Am I missing something in my setup?
