### ISSUE TITLE
How to solution "Error: ENOENT: no such file or directory, open 'yarn.lock'"?

### ISSUE THREAD

**Issue by re-taro** [c-hive/gha-yarn-cache#17]
My project directory tree is like this ↓
```
/
┣/.github/workflows
┗/App ← yarn.lock is in this directory
```
so, I set the `/.github/workflows/main.yml` like this ↓
```yaml
- uses: c-hive/gha-yarn-cache@v1
        with:
          directory: ../App
```
But it doesn't work.
![image](https://user-images.githubusercontent.com/68799469/131874500-93d6a1cf-171e-4948-a5d4-f9d1e04cc553.png)

How can I solution this error?
