### ISSUE TITLE
default working-directory not respected for yarn.lock

### ISSUE THREAD

**Issue by philihp** [c-hive/gha-yarn-cache#21]
I do not mean to shame people who like monorepos, but I have found that this action might not work for them without some additional configuration. The following will fail:

```yaml
# .github/workflows/someproject.yml
name: someproject
on:
  - push

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: someproject
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          # AWS executes lambdas on Node.js 14
          node-version: 14.x
      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn install
      - run: yarn test
```

because it still looks for a yarn.lock in the root. Perhaps in addition to looking at its own config, this action could look at `defaults.run.working-directory` here? https://github.com/c-hive/gha-yarn-cache/blob/b34096df0dc7012080ffce00cf4c288d0925eca5/src/restore.js#L46

As a stopgap, the user can work around by specifying the working directory twice.

```yaml
      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: someproject
```
