### ISSUE TITLE
Cache for pull request actions are incorrect.

### ISSUE THREAD

**Issue by wxsms** [c-hive/gha-yarn-cache#3]
First of all, thank you for the awesome action.

my action file is: https://github.com/uiv-lib/website-v0/blob/master/.github/workflows/pr.yml

```yml
name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: npm run build
```

while a pull request have updated `webpack` from 4 to 5: https://github.com/uiv-lib/website-v0/pull/41

the actions log shows that it's still using webpack 4 for building: https://github.com/uiv-lib/website-v0/runs/1236612708

![image](https://user-images.githubusercontent.com/5960988/96328178-9d853100-1072-11eb-9311-de0d7d449ed3.png)

Not only webpack, other dependencies update have same problem. It works correctly on push, but not pull request.

Do anybody have any sugguestions? thanks in advance.
